name: '${NAME}'
version: '${VERSION}'
main: '${PACKAGE}.WhisperChatPlugin'
loader: '${PACKAGE}.WhisperChatLoader'
authors: ['winlogon']
website: 'https://github.com/WinSMP/WhisperChat'
api-version: 1.21
description: 'Minimalist and no nonsense DM plugin.'
folia-supported: true
permissions:
  whisperchat.admin:
    default: op
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
