name: WhisperChat
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.whisperchat.WhisperChatPlugin'
api-version: 1.21
description: ''
folia-supported: true
permissions:
  whisperchat.dm:
    default: true
  whisperchat.reply:
    default: true
