name: WhisperChat
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.whisperchat.WhisperChatPlugin'
api-version: 1.21
description: ''
folia-supported: true
commands:
  dm:
    description: 'DM someone'
    aliases: 'msgtoggle'
    usage: /<command> <username>
    permission: 'whisperchat.dm'
  r:
    description: 'Reply to someone'
    usage: /<command> <message>
    permission: 'whisperchat.reply'
permissions:
  whisperchat.dm:
    default: true
  whisperchat.reply:
    default: true
