name: EasyVanish
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.whisperchat.WhisperChatPlugin'
api-version: 1.21
description: ''
folia-supported: true
commands:
  dm:
    description: 'DM someone'
    aliases: 'msgtoggle'
    usage: '/vanish'
    permission: 'vanish.vanish'
  r:
    description: 'Reply to someone'
permissions:
  vanish.vanish:
    default: op
  vanish.reload:
    default: op
  vanish.list:
    default: op
